name: hash-id
version: git
summary: Hash Identifier program written in Rust
description: |
  hash-id is a command line program for identifying hash types. 

base: core18
confinement: strict

parts:
  hash-id:
    plugin: rust
    source: .

apps:
  hash-id:
    command: bin/hash-id-rust
    plugs:
      - home
